version: '3'

services:
  # Core API Instance
  gambit_core:
    networks:
      - gambit
    build:
      context: ./gambit-core
      args:
        - VERSION=${GAMBIT_CORE_VERSION}-SNAPSHOT
    image: gambit-core:${GAMBIT_CORE_VERSION}-SNAPSHOT
    restart: always
    ports:
      - ${GAMBIT_CORE_PORT}:8080
    environment:
      - BOT_NAME=${BOT_NAME}

  # Slack Client Passthrough
  slack_client:
    networks:
      - gambit
    build:
      context: ./slack-client
      args:
        - VERSION=${SLACK_CLIENT_VERSION}-SNAPSHOT
    image: slack-client:${SLACK_CLIENT_VERSION}-SNAPSHOT
    restart: always
    depends_on:
      - gambit_core
    environment:
      - SLACK_API_TOKEN=${DEV_SLACK_API_TOKEN}
      - GAMBIT_CORE_URL=http://gambit_core
      - GAMBIT_CORE_PORT=8080

networks:
  gambit:
